[package]
name = "celeste-tray"
version = "0.5.6"
edition = "2021"

[dependencies]
gtk3.workspace = true
hw-msg.workspace = true
lazy_static.workspace = true
libappindicator.workspace = true
libceleste.workspace = true
tr.workspace = true
zbus.workspace = true
