[package]
name = "libceleste"
version = "0.5.4"
edition = "2021"

[lib]
name = "libceleste"

[dependencies]
blocking.workspace = true
futures.workspace = true
glib.workspace = true
tr.workspace = true
